
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
library(glue)
```


### Load Data
```{r}

file <- "./Taipei City Energy Poverty.csv"
raw_data <- read.csv(file, header = TRUE)
raw_data$X2020datanum <- as.integer(raw_data$X2020datanum)
raw_data <- na.omit(raw_data)



# Calculate and  the power per house in to data
power_per_house_2020 <- raw_data$X2020power / raw_data$X2020datanum
summary(power_per_house_2020)
raw_data <- cbind(raw_data, power_per_house_2020)


```



```{r}
# Filter out the outliers of the data (< Q1 or > Q3)
Q1 <- quantile(data$power_per_house_2020, 0.25)
Q3 <- quantile(data$power_per_house_2020, 0.75)
top10percent_value <- quantile(raw_data$power_per_house_2020, 0.90)
IQR <- Q3 - Q1
lower_bound <- Q1 - 1.5 * IQR
upper_bound <- Q3 + 1.5 * IQR

# percentage of data of top10percent
top10percent <- (length(data$power_per_house_2020[data$power_per_house_2020 > top10percent_value]) / length(data$power_per_house_2020)) * 100

# data <- data[data$power_per_house_2020 >= lower_bound & data$power_per_house_2020 <= upper_bound, ]
data <- data[data$power_per_house_2020 <= Q3, ]

# boxplot
boxplot(data$power_per_house_2020, col = "lightblue", border = "brown", horizontal = TRUE)

```



```{r}

# Filter out the outliers of the data

mean_data <- mean(data$power_per_house_2020, na.rm = TRUE)
std_dev_data <- sd(data$power_per_house_2020, na.rm = TRUE)

# Define the lower and upper bounds
lower_bound <- mean_data - 2 * std_dev_data
upper_bound <- mean_data + 2 * std_dev_data

glue("The lower bound is {lower_bound}")
glue("The upper bound is {upper_bound}")
# percentage of data that is under lower_bound
percent_under <- (length(data$power_per_house_2020[data$power_per_house_2020 < lower_bound]) / length(data$power_per_house_2020)) * 100
percent_under

# Filter the data to include only values within 2 standard deviations from the mean
data <- data[data$power_per_house_2020 >= lower_bound & data$power_per_house_2020 <= upper_bound, ]

```

```{r}
data <- raw_data
data <- data[data$power_per_house_2020 <= 10000, ]
# boxplot
boxplot(data$power_per_house_2020, col = "lightblue", border = "brown", horizontal = TRUE)

```

```{r}
library(ggplot2)
plot <- ggplot(data=data, aes(x=X2020income, y=power_per_house_2020)) +
  geom_point() +
  geom_smooth(method="lm", se=TRUE, color="blue", fill="lightblue") +
  labs(title="X-Y Scatter Plot with Regression Line")
plot
```
